# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
    (?x)^(
        command_service/api/outbox_pb2.py|
        command_service/api/outbox_pb2_grpc.py|
        projection_service/adapters/outbox_pb2.py|
        projection_service/adapters/outbox_pb2_grpc.py
    )$


repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [ "--py311-plus" ]
        types: [python]

-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
    -   id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies:
          [
            # "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
          ]

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.5
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

#-   repo: https://github.com/python/black
#    rev: 23.11.0
#    hooks:
#    -   id: black

#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v1.6.1'  # Use the sha / tag you want to point at
#    hooks:
#    -   id: mypy
#        args: [--strict, --install-types, --ignore-missing-imports, --explicit-package-bases]
#        additional_dependencies: [tokenize-rt==3.2.0]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: 3.12.0
    hooks:
    -   id: commitizen
